# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from get_answer import get_answer_pb2 as get__answer_dot_get__answer__pb2


class GetAnswerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Search = channel.unary_unary(
        '/GetAnswer/Search',
        request_serializer=get__answer_dot_get__answer__pb2.SearchRequest.SerializeToString,
        response_deserializer=get__answer_dot_get__answer__pb2.SearchResponse.FromString,
        )


class GetAnswerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Search(self, request, context):
    """Searches for best matching qa pairs for a given query
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetAnswerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=get__answer_dot_get__answer__pb2.SearchRequest.FromString,
          response_serializer=get__answer_dot_get__answer__pb2.SearchResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GetAnswer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
